import { SiteConfig } from '@/types';

export const siteConfig: SiteConfig = {
  name: 'MG Perfume — Haute Parfumerie & Fragrances Orientales à Dakar',
  brandName: 'MG Perfume',
  tagline: 'L’art de séduire sans un mot. Senteurs d’Orient et élixirs de caractère.',
  description: 'Boutique exclusive de parfums authentiques, d’élixirs sensuels et de muscs raffinés à Dakar. Commandez vos fragrances avec livraison express à domicile.',
  url: 'https://mgperfume.sn',
  city: 'Dakar',
  country: 'Sénégal',
  currency: 'FCFA',
  contact: {
    phone: '+221 77 309 48 00',
    phoneFormatted: '77 309 48 00',
    whatsappNumber: '221773094800',
    email: 'mourtadagueye0@gmail.com',
    address: 'Dakar, Sénégal (Boutique & Livraison)',
    hours: 'Lun - Sam : 09h00 - 20h00',
  },
  social: {
    facebook: 'https://www.facebook.com/MGPERFUMEE/',
  },
  shippingZones: [
    { id: 'dakar-centre', name: 'Dakar Centre / Plateau / Fann / Mermoz', price: 2000, delay: 'Sous 2h à 4h' },
    { id: 'almadies-ngor', name: 'Almadies / Ngor / Ouakam / Yoff', price: 2000, delay: 'Sous 2h à 4h' },
    { id: 'banlieue-proche', name: 'Grand Yoff / Liberté / Sacré-Cœur / Parcelles', price: 2500, delay: 'Même jour' },
    { id: 'banlieue-eloignee', name: 'Guédiawaye / Pikine / Rufisque / Keur Massar', price: 3000, delay: '24h' },
    { id: 'regions', name: 'Régions (Thiès, Mbour, Saint-Louis...)', price: 4000, delay: '24h à 48h (GP)' },
  ],
  products: [
    // --- NOUVELLE GAMME SIGNATURE MG PERFUME ---
    {
      id: 'rose-desir',
      name: 'Rose Désir',
      brand: 'MG Perfume',
      tagline: 'Élixir pailleté envoûtant, rose de mai et vanille précieuse',
      price: 20000,
      originalPrice: 25000,
      volume: '50 ml',
      image: '/images/shooting/rose-desir-model.jpg',
      family: 'floral',
      categoryLabel: 'Élixir Féminin',
      badge: 'Coup de Cœur',
      topNotes: ['Pétale de rose', 'Framboise givrée', 'Mandarine'],
      heartNotes: ['Rose de Mai', 'Fleur de pêcher', 'Nacre scintillante'],
      baseNotes: ['Vanille bourbon', 'Bois de santal', 'Musc blanc'],
      description: 'L’incarnation de la féminité absolue. Une eau de parfum lumineuse et nacrée qui sublime le décolleté et enveloppe la peau d’une caresse florale inoubliable.',
      isPopular: true,
    },
    {
      id: 'un-amour',
      name: 'Un Amour',
      brand: 'MG Perfume',
      tagline: 'Sillage doré chaleureux, ambre solaire et fleurs blanches',
      price: 20000,
      volume: '50 ml',
      image: '/images/shooting/un-amour-spray.jpg',
      family: 'oriental',
      categoryLabel: 'Fragrance Noble',
      badge: 'Bestseller',
      topNotes: ['Orange douce', 'Bergamote ensoleillée', 'Miel'],
      heartNotes: ['Jasmin royal', 'Ylang-Ylang', 'Épices douces'],
      baseNotes: ['Ambre précieux', 'Fève Tonka', 'Bois de cèdre'],
      description: 'Une explosion de sensualité et de charme. Conçu pour marquer les mémoires dès la première vaporisation avec un sillage tenace du matin jusqu’au soir.',
      isPopular: true,
    },
    {
      id: 'elixir-gouttes-collection',
      name: 'Coffret Gouttes Sensuelles (4 Elixirs)',
      brand: 'MG Perfume',
      tagline: 'Sublime Vanille • N’aimez Que Moi • Séduction • Profond Désir',
      price: 25000,
      originalPrice: 30000,
      volume: '4 x 30 ml',
      image: '/images/shooting/gamme-gouttes.jpg',
      family: 'gourmand',
      categoryLabel: 'Gamme Huiles & Muscs',
      badge: 'Collection Complète',
      topNotes: ['Vanille sucrée', 'Fraise des bois', 'Caramel', 'Lavande douce'],
      heartNotes: ['Musc intime', 'Pivoine', 'Fleur d’oranger', 'Coco crémeuse'],
      baseNotes: ['Ambroxan', 'Santal blanc', 'Sucre roux', 'Musc pur'],
      description: 'La collection complète des 4 élixirs en flacon compte-gouttes 30ml pour le layering intime. À appliquer sur les points de pulsation pour une tenue maximale.',
      isPopular: true,
    },
    {
      id: 'naimez-que-moi',
      name: 'N’aimez Que Moi (Musk)',
      brand: 'MG Perfume',
      tagline: 'Goutte de séduction intense, rose sucrée et musc enveloppant',
      price: 8000,
      volume: '30 ml',
      image: '/images/shooting/naimez-que-moi-model.jpg',
      family: 'gourmand',
      categoryLabel: 'Élixir Compte-Gouttes',
      badge: 'Tendance',
      topNotes: ['Fraise gourmande', 'Zeste de citron'],
      heartNotes: ['Rose veloutée', 'Barbe à papa', 'Caramel'],
      baseNotes: ['Musc blanc satiné', 'Vanille absolue'],
      description: 'L’art de séduire sans un mot. Une texture huileuse et soyeuse qui fusionne instantanément avec la peau pour un sillage irrésistible.',
      isPopular: true,
    },

    // --- PARFUMERIE DE CRÉATEURS ORIENTAUX ---
    {
      id: 'khamrah-waha',
      name: 'Khamrah Waha',
      brand: 'Lattafa',
      tagline: 'Élixir épicé rafraîchi de brise marine et fève tonka',
      price: 35000,
      originalPrice: 40000,
      volume: '100 ml',
      image: '/images/products/khamrah-waha.jpg',
      family: 'oriental',
      categoryLabel: 'Oriental Épicé Frais',
      badge: 'Bestseller',
      topNotes: ['Concombre', 'Bergamote', 'Yuzu', 'Genévrier'],
      heartNotes: ['Gingembre', 'Iris', 'Sauge', 'Sel de mer'],
      baseNotes: ['Akigalawood', 'Fève Tonka', 'Vanille', 'Musc', 'Ambrofix™'],
      description: 'Une réinterprétation lumineuse alliant la fraîcheur du yuzu et du sel marin à la richesse de la fève tonka et du musc.',
      isPopular: true,
    },
    {
      id: 'seasons-drift',
      name: 'Seasons Drift',
      brand: 'Z / Aoud',
      tagline: 'Sillage boisé noble aux accents de poivre rose et résine d’ambre',
      price: 25000,
      volume: '100 ml',
      image: '/images/products/seasons-drift.jpg',
      family: 'boise',
      categoryLabel: 'Boisé Aromatique',
      topNotes: ['Zeste de citron', 'Poivre rose', 'Pamplemousse'],
      heartNotes: ['Sauge clarée', 'Gingembre', 'Cèdre'],
      baseNotes: ['Labdanum', 'Bois de santal', 'Ambre précieux', 'Résine'],
      description: 'Un parfum d’une tenue remarquable avec une fraîcheur d’agrumes poivrée qui s’ancre dans un lit de santal et d’ambre profond.',
    },
    {
      id: 'mazaaj-infused',
      name: 'Mazaaj Infused',
      brand: 'Z / Aoud',
      tagline: 'Fraîcheur vive d’agrumes infusée d’oliban et d’ambroxan',
      price: 25000,
      volume: '100 ml',
      image: '/images/products/mazaaj-infused.jpg',
      family: 'aquatique',
      categoryLabel: 'Hespéridé & Boisé',
      topNotes: ['Citron', 'Orange', 'Bergamote'],
      heartNotes: ['Néroli', 'Gingembre frais'],
      baseNotes: ['Oliban', 'Ambroxan', 'Notes boisées nobles'],
      description: 'L’accord idéal entre dynamisme solaire et profondeur mystique. Une explosion hespéridée équilibrée par l’encens oliban.',
    },
    {
      id: 'raheeq',
      name: 'Raheeq',
      brand: 'Nusuk',
      tagline: 'Gourmandise miellée, abricot velouté et magnolia précieux',
      price: 25000,
      originalPrice: 30000,
      volume: '100 ml',
      image: '/images/products/raheeq.jpg',
      family: 'gourmand',
      categoryLabel: 'Gourmand Solaire',
      topNotes: ['Citron', 'Miel doré', 'Orange sanguine', 'Abricot'],
      heartNotes: ['Caramel fondant', 'Noix de coco', 'Magnolia'],
      baseNotes: ['Vanille absolue', 'Bois de santal', 'Musc blanc'],
      description: 'Un hymne à la douceur et à l’opulence. Des effluves de miel et d’abricot fondant sur un cœur de caramel vanillé et de magnolia.',
      isPopular: true,
    },
    {
      id: 'souvenir-blooming-bliss',
      name: 'Souvenir Blooming Bliss',
      brand: 'Afnan',
      tagline: 'Dôme d’élégance, noix de coco crémeuse et bois de Palo Santo',
      price: 30000,
      volume: '100 ml',
      image: '/images/products/souvenir-blooming-bliss.jpg',
      family: 'gourmand',
      categoryLabel: 'Boisé Gourmand',
      topNotes: ['Vanille bourbon'],
      heartNotes: ['Noix de coco lactée', 'Caramel', 'Palo Santo'],
      baseNotes: ['Bois de santal', 'Musc blanc pur'],
      description: 'Présenté dans son flacon sphérique d’exception, Blooming Bliss libère une aura crémeuse et mystique avec les nuances du Palo Santo.',
    },
    {
      id: 'mystique-bouquet',
      name: 'Mystique Bouquet',
      brand: 'Afnan',
      tagline: 'Brassée somptueuse de fleurs d’oranger, pêche blanche et litchi',
      price: 30000,
      volume: '100 ml',
      image: '/images/products/mystique-bouquet.jpg',
      family: 'floral',
      categoryLabel: 'Floral Fruité Haute Tenue',
      badge: 'Prestige',
      topNotes: ['Pêche blanche', 'Mandarine juteuse', 'Bergamote', 'Litchi'],
      heartNotes: ['Pivoine royale', 'Fleur d’Oranger', 'Mahonia', 'Vétiver'],
      baseNotes: ['Musc soyeux', 'Ambroxan', 'Mousse de chêne', 'Vanille'],
      description: 'Une fragrance raffinée et sensuelle qui capture la fraîcheur des vergers ensoleillés avant de s’épanouir sur un sillage poudré.',
    },
  ],
};
