import { SiteConfig } from '@/types';

export const siteConfig: SiteConfig = {
  name: 'MG Perfume — Haute Parfumerie & Fragrances Orientales à Dakar',
  brandName: 'MG Perfume',
  tagline: 'L’art de séduire sans un mot. Senteurs d’Orient et élixirs de caractère.',
  description: 'Boutique exclusive de parfums authentiques, d’élixirs sensuels et de muscs raffinés à Dakar. Commandez vos fragrances avec livraison express à domicile.',
  url: 'https://www.mg-perfume.com',
  city: 'Dakar',
  country: 'Sénégal',
  currency: 'FCFA',
  contact: {
    phone: '+221 77 309 48 00',
    phoneFormatted: '77 309 48 00',
    whatsappNumber: '221773094800',
    email: 'mourtadagueye0@gmail.com',
    address: 'Dakar, Sénégal (Boutique & Livraison)',
    hours: 'Lun - Sam : 09h00 - 20h00',
  },
  social: {
    facebook: 'https://www.facebook.com/MGPERFUMEE/',
  },
  shippingZones: [
    { id: 'dakar-centre', name: 'Dakar Centre / Plateau / Fann / Mermoz', price: 2000, delay: 'Sous 2h à 4h' },
    { id: 'almadies-ngor', name: 'Almadies / Ngor / Ouakam / Yoff', price: 2000, delay: 'Sous 2h à 4h' },
    { id: 'banlieue-proche', name: 'Grand Yoff / Liberté / Sacré-Cœur / Parcelles', price: 2500, delay: 'Même jour' },
    { id: 'banlieue-eloignee', name: 'Guédiawaye / Pikine / Rufisque / Keur Massar', price: 3000, delay: '24h' },
    { id: 'regions', name: 'Régions (Thiès, Mbour, Saint-Louis...)', price: 4000, delay: '24h à 48h (GP)' },
  ],
  editorialBanners: [
    {
      id: 'naimez-que-moi',
      tag: 'Senteurs d’Orient',
      title: 'ÉLIXIRS & GOUTTES INTIMES',
      image: '/images/shooting/naimez-que-moi-model.jpg',
      alt: 'Mannequin MG Perfume N’aimez Que Moi',
      linkText: 'Découvrir la collection',
      href: '/boutique',
      bgColor: '#0E2A1A',
    },
    {
      id: 'rose-desir',
      tag: 'Élixirs du Moment',
      title: 'FRAGRANCES FÉMININES',
      image: '/images/shooting/rose-desir-model.jpg',
      alt: 'Shooting Rose Désir MG Perfume',
      linkText: 'Explorer les créations',
      href: '/boutique',
      bgColor: '#350B14',
    },
    {
      id: 'un-amour',
      tag: 'Le Geste & Le Sillage',
      title: 'L’ART DU VAPORISATEUR',
      image: '/images/shooting/un-amour-spray.jpg',
      alt: 'Vaporisation Parfum Un Amour MG Perfume',
      linkText: 'Voir la boutique',
      href: '/boutique',
      bgColor: '#250810',
    },
    {
      id: 'gamme-gouttes',
      tag: 'Rituel de Layering',
      title: 'HUILES & MUSCS INTENSES',
      image: '/images/shooting/gamme-gouttes.jpg',
      alt: 'Podium Huiles et Muscs MG Perfume',
      linkText: 'Découvrir les muscs',
      href: '/boutique',
      bgColor: '#0E1E38',
    },
  ],
  faqs: [
    {
      q: 'Comment s’effectue la livraison à Dakar ?',
      a: 'Nos livreurs vous remettent votre commande directement en main propre à domicile ou au bureau dans un délai de 2h à 4h.',
    },
    {
      q: 'Quels sont les modes de paiement acceptés ?',
      a: 'Vous réglez à la livraison en espèces, par Wave ou via Orange Money après vérification de votre colis.',
    },
    {
      q: 'Livrez-vous dans les régions du Sénégal ?',
      a: 'Oui, nous expédions dans toutes les régions (Thiès, Saint-Louis, Mbour, Ziguinchor...) via les services GP ou transporteurs partenaires en 24h à 48h.',
    },
    {
      q: 'Les parfums sont-ils des originaux ?',
      a: 'Absolument. Tous nos parfums sont 100% originaux, neufs et scellés dans leur boîte d’origine.',
    },
  ],
  products: [
    // --- PARFUMERIE DE CRÉATEURS ORIENTAUX ---
    {
      id: 'khamrah-waha',
      name: 'Khamrah Waha',
      brand: 'Lattafa',
      tagline: 'Élixir épicé rafraîchi de brise marine et fève tonka',
      price: 35000,
      originalPrice: 40000,
      volume: '100 ml',
      image: '/images/products/khamrah-waha.jpg',
      family: 'oriental',
      categoryLabel: 'Oriental Épicé Frais',
      badge: 'Bestseller',
      topNotes: ['Concombre', 'Bergamote', 'Yuzu', 'Genévrier'],
      heartNotes: ['Gingembre', 'Iris', 'Sauge', 'Sel de mer'],
      baseNotes: ['Akigalawood', 'Fève Tonka', 'Vanille', 'Musc', 'Ambrofix™'],
      description: 'Une réinterprétation lumineuse alliant la fraîcheur du yuzu et du sel marin à la richesse de la fève tonka et du musc.',
      isPopular: true,
    },
    {
      id: 'seasons-drift',
      name: 'Seasons Drift',
      brand: 'Z / Aoud',
      tagline: 'Sillage boisé noble aux accents de poivre rose et résine d’ambre',
      price: 25000,
      volume: '100 ml',
      image: '/images/products/seasons-drift.jpg',
      family: 'boise',
      categoryLabel: 'Boisé Aromatique',
      topNotes: ['Zeste de citron', 'Poivre rose', 'Pamplemousse'],
      heartNotes: ['Sauge clarée', 'Gingembre', 'Cèdre'],
      baseNotes: ['Labdanum', 'Bois de santal', 'Ambre précieux', 'Résine'],
      description: 'Un parfum d’une tenue remarquable avec une fraîcheur d’agrumes poivrée qui s’ancre dans un lit de santal et d’ambre profond.',
    },
    {
      id: 'mazaaj-infused',
      name: 'Mazaaj Infused',
      brand: 'Z / Aoud',
      tagline: 'Fraîcheur vive d’agrumes infusée d’oliban et d’ambroxan',
      price: 25000,
      volume: '100 ml',
      image: '/images/products/mazaaj-infused.jpg',
      family: 'aquatique',
      categoryLabel: 'Hespéridé & Boisé',
      topNotes: ['Citron', 'Orange', 'Bergamote'],
      heartNotes: ['Néroli', 'Gingembre frais'],
      baseNotes: ['Oliban', 'Ambroxan', 'Notes boisées nobles'],
      description: 'L’accord idéal entre dynamisme solaire et profondeur mystique. Une explosion hespéridée équilibrée par l’encens oliban.',
    },
    {
      id: 'raheeq',
      name: 'Raheeq',
      brand: 'Nusuk',
      tagline: 'Gourmandise miellée, abricot velouté et magnolia précieux',
      price: 25000,
      originalPrice: 30000,
      volume: '100 ml',
      image: '/images/products/raheeq.jpg',
      family: 'gourmand',
      categoryLabel: 'Gourmand Solaire',
      topNotes: ['Citron', 'Miel doré', 'Orange sanguine', 'Abricot'],
      heartNotes: ['Caramel fondant', 'Noix de coco', 'Magnolia'],
      baseNotes: ['Vanille absolue', 'Bois de santal', 'Musc blanc'],
      description: 'Un hymne à la douceur et à l’opulence. Des effluves de miel et d’abricot fondant sur un cœur de caramel vanillé et de magnolia.',
      isPopular: true,
    },
    {
      id: 'souvenir-blooming-bliss',
      name: 'Souvenir Blooming Bliss',
      brand: 'Afnan',
      tagline: 'Dôme d’élégance, noix de coco crémeuse et bois de Palo Santo',
      price: 30000,
      volume: '100 ml',
      image: '/images/products/souvenir-blooming-bliss.jpg',
      family: 'gourmand',
      categoryLabel: 'Boisé Gourmand',
      topNotes: ['Vanille bourbon'],
      heartNotes: ['Noix de coco lactée', 'Caramel', 'Palo Santo'],
      baseNotes: ['Bois de santal', 'Musc blanc pur'],
      description: 'Présenté dans son flacon sphérique d’exception, Blooming Bliss libère une aura crémeuse et mystique avec les nuances du Palo Santo.',
    },
    {
      id: 'mystique-bouquet',
      name: 'Mystique Bouquet',
      brand: 'Afnan',
      tagline: 'Brassée somptueuse de fleurs d’oranger, pêche blanche et litchi',
      price: 30000,
      volume: '100 ml',
      image: '/images/products/mystique-bouquet.jpg',
      family: 'floral',
      categoryLabel: 'Floral Fruité Haute Tenue',
      badge: 'Prestige',
      topNotes: ['Pêche blanche', 'Mandarine juteuse', 'Bergamote', 'Litchi'],
      heartNotes: ['Pivoine royale', 'Fleur d’Oranger', 'Mahonia', 'Vétiver'],
      baseNotes: ['Musc soyeux', 'Ambroxan', 'Mousse de chêne', 'Vanille'],
      description: 'Une fragrance raffinée et sensuelle qui capture la fraîcheur des vergers ensoleillés avant de s’épanouir sur un sillage poudré.',
    },
  ],
};
